feat: update color scheme, migrate few of the existing components to shadcn
getAlby/nostr-wallet-connect-next pull request #188
Opened 2024-04-02 11:17 UTC by pavanjoshi914

update text colors whereever necessary
migrate existing components to shadcn
1. Permissions component
2. setup wallet component
3. Backup component
4. import component
5. connect app component
6. channels component
7. custom channels component
8 App created component

2024-04-02 11:24 UTC, pavanjoshi914 commented
i migrated only those which had dark color prefixes and needed migration to eliminate dark prefixes/  just to keep pr small and have dark prefixes eliminated.

the next task could be have only single source for text color. for eg. we have many text-gray text-neutral instances. i think every color should be referenced up from the source index.css file itself

2024-04-02 11:54 UTC, reneaaron commented on frontend/src/screens/channels/NewCustomChannel.tsx
> +              {loading ? "Loading..." : "Open Channel"}
Use LoadingButton

2024-04-02 12:06 UTC, reneaaron requested changes

2024-04-02 12:06 UTC, reneaaron commented on frontend/src/screens/setup/SetupWallet.tsx
> +              <Link to={`/setup/finish`}>
When is this stuff being shown?

2024-04-02 12:06 UTC, reneaaron commented on frontend/src/screens/channels/NewCustomChannel.tsx
>                <label
Use label & input from shadcn

2024-04-02 12:06 UTC, reneaaron commented on frontend/src/screens/channels/NewCustomChannel.tsx
> +      <h2 className="font-bold text-2xl mt-5">Open a channel</h2>
Use AppHeader

2024-04-02 12:06 UTC, reneaaron commented on frontend/src/screens/channels/Channels.tsx
> +                  <div className="h-2.5 bg-primary rounded-full w-1/3 mr-5"></div>
Use Skeletons & implement a proper loading state

2024-04-02 12:06 UTC, reneaaron commented on frontend/src/screens/apps/NewApp.tsx
> +              <label htmlFor="name" className="block font-medium">
Use shadcn label

2024-04-02 12:06 UTC, reneaaron commented on frontend/src/screens/apps/AppCreated.tsx
> +        <Card className="relative">
Use Dialog instead of cards https://ui.shadcn.com/docs/components/dialog

2024-04-02 12:06 UTC, reneaaron commented on frontend/src/screens/BackupMnemonic.tsx
>                <label
Use shadcn label

2024-04-02 12:06 UTC, reneaaron commented on frontend/src/components/Permissions.tsx
> +                                <Card>
I don't think this should be cards. It semantically doesn't fit and feels a bit like a hack. 

Better leave this as is and think about how this should look in future (maybe we also revert back to some more classical form components somewhen).

2024-04-02 12:46 UTC, pavanjoshi914 commented on frontend/src/screens/channels/NewCustomChannel.tsx
> +            </Button>
resolved

2024-04-02 12:48 UTC, pavanjoshi914 commented on frontend/src/screens/setup/SetupWallet.tsx
> +              <Link to={`/setup/finish`}>
if there is any preconfigured backend type then it's shown on same setup wallet screen

2024-04-02 13:10 UTC, pavanjoshi914 commented on frontend/src/screens/channels/NewCustomChannel.tsx
> +      <h2 className="font-bold text-2xl mt-5">Open a channel</h2>
resolved

2024-04-02 13:16 UTC, pavanjoshi914 commented on frontend/src/screens/apps/NewApp.tsx
> +              <label htmlFor="name" className="block font-medium">
resolved

2024-04-02 13:40 UTC, pavanjoshi914 commented on frontend/src/screens/apps/AppCreated.tsx
> +        <Card className="relative">
resolved

2024-04-03 05:12 UTC, pavanjoshi914 commented on frontend/src/components/Permissions.tsx
> +                                <Card>
resolved

2024-04-03 05:50 UTC, pavanjoshi914 commented on frontend/src/screens/channels/Channels.tsx
> +                  <div className="h-2.5 bg-primary rounded-full w-1/3 mr-5"></div>
maybe we can just use simple loading circle at the center and remove this?

2024-04-03 05:51 UTC, pavanjoshi914 commented on frontend/src/screens/channels/Channels.tsx
> +                  <div className="h-2.5 bg-primary rounded-full w-1/3 mr-5"></div>
![Uploading image.png…]()

2024-04-04 11:37 UTC, reneaaron commented on frontend/src/screens/channels/Channels.tsx
> +                  <div className="h-2.5 bg-primary rounded-full w-1/3 mr-5"></div>
Sure

2024-04-04 11:38 UTC, reneaaron commented on frontend/src/screens/setup/SetupWallet.tsx
> +                  className={`mt-4 px-3 py-2`}
no custom paddings for buttons

2024-04-04 11:39 UTC, reneaaron commented on frontend/src/screens/setup/SetupWallet.tsx
> +                        <ChevronRight className="w-8 h-8 text-gray-400" />
Remove gray & use semantic classes (e.g. muted)

2024-04-04 11:40 UTC, reneaaron commented on frontend/src/screens/channels/NewCustomChannel.tsx
> +              {loading ? "Loading..." : "Open Channel"}
I don't think we want that. If at all that should be a behavior of the LoadingButton.

```suggestion
             Open Channel
```

2024-04-04 11:41 UTC, reneaaron commented on frontend/src/screens/channels/NewCustomChannel.tsx
> +      <Card className="p-4">
Why custom paddings for cards?

2024-04-04 11:46 UTC, reneaaron requested changes

2024-04-04 11:46 UTC, reneaaron commented on frontend/src/screens/apps/ShowApp.tsx
> +                    <img
Create a component for this AppAvatar

2024-04-04 11:46 UTC, reneaaron commented on frontend/src/screens/BackupMnemonic.tsx
> +                className="ms-2 text-sm font-medium text-primary"
Do we really need text-primary here? Please take a look at the examples from shadcn...

2024-04-10 08:56 UTC, pavanjoshi914 commented on frontend/src/screens/channels/Channels.tsx
> +                  <div className="h-2.5 bg-primary rounded-full w-1/3 mr-5"></div>
resolved

2024-04-10 09:10 UTC, pavanjoshi914 commented on frontend/src/screens/setup/SetupWallet.tsx
> +                  className={`mt-4 px-3 py-2`}
resolved

2024-04-10 09:10 UTC, pavanjoshi914 commented on frontend/src/screens/setup/SetupWallet.tsx
> +                        <ChevronRight className="w-8 h-8 text-gray-400" />
resolved

2024-04-10 09:11 UTC, pavanjoshi914 commented on frontend/src/screens/channels/NewCustomChannel.tsx
> +              {loading ? "Loading..." : "Open Channel"}
it's just that when loading we show loading text along with loader we can default to open channel. resolved

2024-04-10 09:36 UTC, pavanjoshi914 commented on frontend/src/screens/apps/ShowApp.tsx
> +                    <img
resolved

2024-04-10 09:45 UTC, pavanjoshi914 commented on frontend/src/screens/BackupMnemonic.tsx
> +                className="ms-2 text-sm font-medium text-primary"
resolved

2024-04-11 11:42 UTC, reneaaron approved these changes
Added some more fixes, still migration is not complete quite some colors being used in those files. :man_shrugging:

2024-04-12 05:36 UTC, pavanjoshi914 commented
yup! we can't remove those without using something from shadcn or having some other design. so I kept as it is for now. maybe let's ask Jakub for designs. i didn't find any relevant component  in shadcn to do the same except cards. merging this for now

2024-04-12 05:36 UTC, merged